site_name: Nextcloud from Scratch
site_url: https://nextcloud-from-scratch.readthedocs.io
nav:
    - Home: index.md
    - About: about.md
    - Getting Started: getting-started.md
    - Prepare System: prepare-system.md
    - Install Nextcloud: install-nextcloud.md
    - Configure Nextcloud: configure-nextcloud.md
theme:
    name: readthedocs
